### ISSUE TITLE
loadfile()

### ISSUE THREAD

**Issue by HrClausen** [jbaiter/chdkptp.py#1]
To run a lua script on the camera, one needs to use loadfile(). This function does not seem to be lifted to the python interface.

http://chdk.setepontos.com/index.php?topic=9507.0

**Comment by jbaiter** [comment]
Are you sure that this function is still in the chdkptp API? I can't find a mention of it anywhere in the source code.
For running Lua scripts on the camera, you can just use the `lua_execute` method on the device object (http://chdkptppy.readthedocs.org/en/latest/#chdkptp.ChdkDevice.lua_execute).

**Comment by HrClausen** [comment]
My mistake. I thought loadfile was a chdkptp command. It is actually a lua command.
